// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8QN41C8IzYTKZ_BxLnZHDiVAA9uL_e0U',
    appId: '1:115110310383:web:21b5e6d9ef1b98d04cc61a',
    messagingSenderId: '115110310383',
    projectId: 'sleep-sync-94e9a',
    authDomain: 'sleep-sync-94e9a.firebaseapp.com',
    storageBucket: 'sleep-sync-94e9a.firebasestorage.app',
    measurementId: 'G-HXH33K02R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf912egG4aPBwLzkB4OYjZm2cPNEzO8YY',
    appId: '1:115110310383:android:cf6d6b30d7e126b04cc61a',
    messagingSenderId: '115110310383',
    projectId: 'sleep-sync-94e9a',
    storageBucket: 'sleep-sync-94e9a.firebasestorage.app',
  );
}
